#! /bin/sh
#
# This is an init script for openembedded

TRANSOPTIONS="-g /var/lib/transmission-daemon"
# load default values
[ -f /etc/default/transmission-daemon ] && . /etc/default/transmission-daemon

[ -z "$DAEMON_USER" ] || SSDOPTIONS="--chuid $DAEMON_USER:$DAEMON_GROUP"

case "$1" in
  start)
    echo  "Starting transmission-daemon"
    /sbin/start-stop-daemon $SSDOPTIONS --start --quiet --exec /usr/bin/transmission-daemon -- $TRANSOPTIONS
    ;;
  stop)
    echo  "Stopping transmission-daemon"
    /sbin/start-stop-daemon --stop --quiet --exec /usr/bin/transmission-daemon
    ;;
  restart)
    echo -n "Stopping transmission-daemon"
    /sbin/start-stop-daemon --stop --quiet --exec /usr/bin/transmission-daemon
    for i in 1 2 3 ;
    do
        sleep 1
        echo -n "."
    done
    echo  "Restarting transmission-daemon" 
    /sbin/start-stop-daemon $SSDOPTIONS --start --quiet --exec /usr/bin/transmission-daemon -- $TRANSOPTIONS
    ;;
  *)
    echo "Usage: /etc/init.d/tranmission {start|stop|restart}"
    exit 1
esac

exit 0
