#!/bin/sh
#
# rcS		Call all S??* scripts in /etc/rcS.d in
#		numerical/alphabetical order.
#
# Version:	@(#)/etc/init.d/rcS  2.76  19-Apr-1999  miquels@cistron.nl
#

PATH=/sbin:/bin:/usr/sbin:/usr/bin
runlevel=S
prevlevel=N
umask 022
export PATH runlevel prevlevel

#
# if no rtc try to guess a reasonable time
#  < 01.01.2004
# /etc/fakeRTC is updated by enigma2 and enigma2.sh
#
if [ `date +%s` -lt 1072224000 ] ; then
    F=/etc/fakeRTC
    [ ! -f $F ] && F=/etc/resolv.conf
    date -s `date "+%Y%m%d%H%M.%S" -r $F`
fi

#	Make sure proc is mounted
#
[ -d "/proc/1" ] || mount /proc

#
#	Source defaults.
#
. /etc/default/rcS

#
#	Trap CTRL-C &c only in this shell so we can interrupt subprocesses.
#
trap ":" INT QUIT TSTP

#
#	Call all parts in order.
#
exec /etc/init.d/rc S


