#@TYPE: Machine
#@NAME: Vu+ Duo4klite
#@DESCRIPTION: Machine configuration for the Vu+ Duo4klite

SOC_FAMILY = "bcm7252s"
CHIPSET = "bcm7252s"

BRAND_OEM = "vuplus"
MACHINE_BRAND = "Vu+"
MACHINE_NAME = "Duo4kLite"

FLASHSIZE = "1024"

MTD_KERNEL = "mmcblk0p4"
MTD_ROOTFS = "mmcblk0p13"
MULTIBOOT_STARTUP_DEFAULT ?= "STARTUP_1"
KERNEL_FILE = "kernel_auto.bin"
ROOTFS_FILE = "rootfs.tar.bz2"
MTD_BOOTFS = "mmcblk0p1"
MTD_BLACK  = "mmcblk0"

IMAGE_FSTYPES =+ "tar.bz2"
IMAGE_CLASSES += " image_types_bz2_gb_splash_initrd"
IMAGE_UNPACK_PATH = "vuplus/duo4klite"

MACHINE_FEATURES += " HDMI HDMI-IN-FHD hdmi-in-helper colorlcd400 ci dvb-c blindscan-dvbc blindscan-dvbs skins1080 webkithbbtv ctrlrc transcoding streamproxy dvbproxy mmc emmc fcc quadpip bluetooth chromiumos vu-eglfs"
OPENPLI_FEATURES += " kodi"

UPDATE_DIR = "duo4klite"

require conf/machine/include/vuxxo4klite.inc

require conf/machine/include/vuplus-bz2-gb-splash-initrd.inc

DVBMEDIASINK_CONFIG = "--with-dtsdownmix --with-dts --with-pcm --with-eac3 --with-amr --with-wmv --with-vb6 --with-vb8 --with-vb9 --with-spark --with-h265"

IMAGE_INSTALL:append = "\
	vuplus-initrd-${MACHINE} \
	enigma2-plugin-systemplugins-bluetoothsetup \
	vuplus-bluetooth-util-${MACHINE} \
"

FORCE_REBOOT_OPTION = "reboot"

MACHINE_KERNEL_PR = "r0"

PREFERRED_VERSION_linux-${MACHINE} = "4.1.20"
PREFERRED_VERSION_hmp-usb-dvb-t2-c-arm = "V160430"
